#!/usr/bin/env python3
import csv
import json

from parse import *
from config import Config

root = "."
config = Config(root)

dat = read_packages(os.path.join(root, "data"), config)
repos = build_repo_map(dat)
resolve_dependencies(dat, repos)
add_extra_metadata(dat, config)

write_repos(dat, config)
